### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mahmoud** [xstate-wizards/xstate-wizards#78]
I noticed that xstate-wizards doesn't have a `LICENSE` file, yet. I understand in early development it can be hard to choose. Here's a useful resource on the topic (which could probably be written in xstate-wizards, too): https://choosealicense.com/

I've had quite a bit of experience in this space, and would be happy to chat more on your options. I'd love to see a BSD/MIT, or even Apache. And it's always good to remember you can change it later, as your requirements change, too.

**Comment by youmustfight** [comment]
Thanks for mentioning! I've been inclined to set MIT as the license. For a moment I was exploring other licenses to ensure organizations had to push updates back into the packages, but the legal overhead doesn't was worth it. I talked with tech teams working in state/federal governments and I don't want to give them headaches if they need to adapt the packages to work in legacy systems.

**Comment by youmustfight** [comment]
Added the MIT license! Appreciate your thoughts and input!

**Comment by mahmoud** [comment]
Excellent choice, thanks for the quick resolution!
